[pytest]
DJANGO_SETTINGS_MODULE = core_config.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --ds=core_config.settings --reuse-db --ignore=test_flow.py --ignore=test_sesion.py --ignore=api/management/commands/seed_sesiones_test.py
norecursedirs = venv .venv .git
